- updated serial generation to confirm that there is no duplicate created - updated temp file creation to common function and made it so die() will   remove all leftover temp files

diff --git a/pca b/pca
--- a/pca
+++ b/pca
@@ -24,11 +24,22 @@ OS="openssl"
 function die {
 	local _rc=${1:?1}; shift;
 	local _out=$*
-#XXX clean up any temporary files
+	rm -f /tmp/$NAME-temp.*
 	if [ ! -z "$_out" ]; then
 		echo "$_out"
 	fi
 	exit $_rc 
+}
+
+function newtmp {
+	local _failmsg=$*
+	local _tf
+	_tf=`mktemp -q /tmp/$NAME-temp.XXXXXXXX`
+	if [ $? -ne 0 ]; then
+		die 1 "$_failmsg"
+	fi
+	echo $_tf
+	return 0
 }
 
 function syntax {
@@ -125,10 +136,16 @@ function read_from_stdin {
 
 function prep_serial {
 	local _ca=$1; shift;
+	local _sn=""
 	[ -z "$_ca" ] && return 1
 	# create a random serial number.
-# XXX though unlikely, we should probably verify it hasn't been used
-	$OS rand -hex 8 > $DBDIR/serial.txt
+	while [ -z "$_sn" ]; do
+		_sn=`$OS rand -hex 8 | tr "[[:lower:]]" "[[:upper:]]"`
+		if [ -f $LIBDIR/$_sn.pem ]; then
+			_sn=""
+		fi
+	done
+	echo $_sn > $DBDIR/serial.txt
 	return 0
 }
 
@@ -303,7 +320,7 @@ function build_config {
 				;;
 		esac
 	done
-	_tf=`mktemp` || die 1 "build_config: mktemp"
+	_tf=`newtmp "build_config: newtmp"`
 	echo # generated config > $_tf
 	cat $CAHOME/config/macros >> $_tf
 	if [ -z "$_prog" -o ! -f $CAHOME/config/prog_$_prog ]; then
@@ -386,7 +403,7 @@ function key_pass {
 	[ -z "$_ca" ] && return 1
 	local _n=$1; shift
 	[ -z "$_n" ] && return 1
-	local _tf=`mktemp -p $KEYDIR $_n.XXXXXX` || die 1 "key_pass: mktemp"
+	local _tf=`newtmp "key_pass: newtmp"`
 	$OS rand -hex 16 > $_tf
 	mv -f $_tf $KEYDIR/$_n.pass || return 1
 	return 0
@@ -427,7 +444,7 @@ function create_key {
 		echo "error generating key pass"
 		return 1
 	fi
-	local _tf=`mktemp -p $KEYDIR $_n.XXXXXX` || die 1 "create_key: mktemp"
+	local _tf=`newtmp "create_key: newtmp"`
 	$OS genrsa -out $_tf $_bits >/dev/null 2>&1
 	$OS rsa -aes256 -passout file:$KEYDIR/$_n.pass -in $_tf -out $KEYDIR/$_n.key >/dev/null 2>&1
 	rm -f $_tf
@@ -644,7 +661,7 @@ function create_req {
 	if [ -z "$_days" ]; then
 		_days=$CERTDAYS
 	fi
-	local _tf=`mktemp -p $REQDIR $_n.XXXXXX` || die 1 "create_req: mktemp"
+	local _tf=`newtmp "create_req: newtmp"`
 	# create req_file
 	echo "# DN attrs for $_n" > $_tf
 	[ ! -z "$_co" ] && echo "countryName=$_co" >> $_tf
@@ -801,7 +818,7 @@ function set_config {
 		echo "can only specify value or delete, not both"
 		return 1
 	fi
-	_tf=`mktemp` || die 1 "set_config: mktemp"
+	_tf=`newtmp "set_config: newtmp"`
 	if [ $_adm -eq 0 ]; then
 		cat $CAHOME/config/$_n | sed -r "s~(^$_k[[:space:]]*=[[:space:]]*).*~\1$_v~" > $_tf
 		echo "$_k=$_v" >&2
@@ -1167,7 +1184,7 @@ function get_pass_from_input {
 		echo "nothing to do"
 		return 1
 	fi
-	_pf=`mktemp tmp.XXXXXXXX` || die 1 "export_pkcs12: mktemp"
+	_pf=`newtmp "export_pkcs12: newtmp"`
 	case "$_p" in
 		-) # read from stdin
 			_p=`read_from_stdin "Enter Password:" -noecho`
