update all external progs to use which to figure out path.

diff --git a/pca b/pca
--- a/pca
+++ b/pca
@@ -2,7 +2,7 @@
 
 # Personal Certificate Authority
 #
-# Copyright (c) 2024 Michael Graves <mg@brainfat.net>
+# Copyright (c) 2026 Michael Graves <mg@brainfat.net>
 #
 # Permission to use, copy, modify, and distribute this software for any
 # purpose with or without fee is hereby granted, provided that the above
@@ -17,14 +17,28 @@
 # OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 #
 
-VER=1.4
+VER=1.5
 NAME=${0##*/}
-OS="openssl"
+OS=$(which openssl)
+RM=$(which rm)
+MKTEMP=$(which mktemp)
+CAT=$(which cat)
+MKDIR=$(which mkdir)
+TOUCH=$(which touch)
+MV=$(which mv)
+CP=$(which cp)
+TAR=$(which tar)
+SED=$(which sed)
+GREP=$(which grep)
+EGREP=$(which egrep)
+TR=$(which tr)
+CUT=$(which cut)
+CHMOD=$(which chmod)
 
 function die {
 	local _rc=${1:?1}; shift;
 	local _out=$*
-	rm -rf /tmp/$NAME-temp.*
+	${RM} -rf /tmp/$NAME-temp.*
 	if [ ! -z "$_out" ]; then
 		echo "$_out"
 	fi
@@ -34,7 +48,7 @@ function die {
 function newtmpd {
 	local _failmsg=$*
 	local _tf
-	_tf=`mktemp -d -q /tmp/$NAME-temp.XXXXXXXX`
+	_tf=`${MKTEMP} -d -q /tmp/$NAME-temp.XXXXXXXX`
 	if [ $? -ne 0 ]; then
 		die 1 "$_failmsg"
 	fi
@@ -45,7 +59,7 @@ function newtmpd {
 function newtmp {
 	local _failmsg=$*
 	local _tf
-	_tf=`mktemp -q /tmp/$NAME-temp.XXXXXXXX`
+	_tf=`${MKTEMP} -q /tmp/$NAME-temp.XXXXXXXX`
 	if [ $? -ne 0 ]; then
 		die 1 "$_failmsg"
 	fi
@@ -154,7 +168,7 @@ function prep_serial {
 	[ -z "$_ca" ] && return 1
 	# create a random serial number.
 	while [ -z "$_sn" ]; do
-		_sn=`$OS rand -hex 8 | tr "[[:lower:]]" "[[:upper:]]"`
+		_sn=`$OS rand -hex 8 | ${TR} "[[:lower:]]" "[[:upper:]]"`
 		if [ -f $LIBDIR/$_sn.pem ]; then
 			_sn=""
 		fi
@@ -201,18 +215,18 @@ function init_ca {
 		echo "CA $_ca already exists"
 		return 1
 	fi
-	mkdir -p $_root
-	mkdir $_root/certs
-	mkdir $_root/requests
-	mkdir $_root/db
-	touch $_root/db/serial.txt
-	touch $_root/db/index.txt
-	touch $_root/db/index.txt.attr
-	mkdir $_root/db/library
-	mkdir $_root/crl
-	mkdir $_root/private
-	mkdir $_root/config
-	cat <<EOF> $_root/config/macros
+	${MKDIR} -p $_root
+	${MKDIR} $_root/certs
+	${MKDIR} $_root/requests
+	${MKDIR} $_root/db
+	${TOUCH} $_root/db/serial.txt
+	${TOUCH} $_root/db/index.txt
+	${TOUCH} $_root/db/index.txt.attr
+	${MKDIR} $_root/db/library
+	${MKDIR} $_root/crl
+	${MKDIR} $_root/private
+	${MKDIR} $_root/config
+	${CAT} <<EOF> $_root/config/macros
 # Personal Certificate Authority config
 #
 CAHOME=$_root
@@ -238,7 +252,7 @@ PUBLICURL=http://127.0.0.1/ca
 PATHLEN=1
 EOF
 
-	cat <<EOF> $_root/config/prog_ca
+	${CAT} <<EOF> $_root/config/prog_ca
 dir				= \$ENV::CAHOME
 certs			= \$ENV::CERTDIR
 crl_dir			= \$ENV::CRLDIR
@@ -255,14 +269,14 @@ default_days	= \$ENV::CERTDAYS
 string_mask		= utf8only
 EOF
 
-	cat <<EOF> $_root/config/prog_req
+	${CAT} <<EOF> $_root/config/prog_req
 default_days	= \$ENV::CERTDAYS
 default_bits	= \$ENV::DEFBITS
 default_md		= \$ENV::DEFMD
 string_mask		= utf8only
 prompt			= no
 EOF
-	cat <<EOF> $_root/config/req_dn
+	${CAT} <<EOF> $_root/config/req_dn
 countryName                     = Country Name (2 letter code)
 countryName_default             = XX
 countryName_min                 = 2
@@ -279,13 +293,13 @@ commonName_max                  = 64
 emailAddress                    = Email Address
 emailAddress_max                = 64
 EOF
-	cat <<EOF> $_root/config/req_attrs
+	${CAT} <<EOF> $_root/config/req_attrs
 #challengePassword               = A challenge password
 #challengePassword_min           = 4
 #challengePassword_max           = 20
 #unstructuredName                = An optional company name
 EOF
-	cat <<EOF> $_root/config/policy_match
+	${CAT} <<EOF> $_root/config/policy_match
 countryName=match
 stateOrProvinceName=optional
 localityName=optional
@@ -295,7 +309,7 @@ commonName=supplied
 emailAddress=optional
 subjectAltName=optional
 EOF
-	cat <<EOF> $_root/config/policy_sign
+	${CAT} <<EOF> $_root/config/policy_sign
 countryName=optional
 stateOrProvinceName=optional
 localityName=optional
@@ -305,14 +319,14 @@ commonName=supplied
 emailAddress=optional
 subjectAltName=optional
 EOF
-	cat <<EOF> $_root/config/extension_ca
+	${CAT} <<EOF> $_root/config/extension_ca
 basicConstraints = critical,CA:TRUE,pathlen:\$ENV::PATHLEN
 keyUsage = critical,keyCertSign,cRLSign
 subjectKeyIdentifier = hash
 crlDistributionPoints = URI:\$ENV::PUBLICURL/\$ENV::ROOTCRL
 EOF
 
-	cat <<EOF> $_root/config/extension_cert
+	${CAT} <<EOF> $_root/config/extension_cert
 basicConstraints = critical,CA:FALSE
 keyUsage = nonRepudiation,digitalSignature,keyEncipherment
 extendedKeyUsage = serverAuth,clientAuth,emailProtection
@@ -360,10 +374,10 @@ function build_config {
 	done
 	_tf=`newtmp "build_config: newtmp"`
 	echo # generated config > $_tf
-	cat $CAHOME/config/macros >> $_tf
+	${CAT} $CAHOME/config/macros >> $_tf
 	if [ -z "$_prog" -o ! -f $CAHOME/config/prog_$_prog ]; then
 		echo "missing program or config not found"
-		rm -f $_tf
+		${RM} -f $_tf
 		return 1
 	fi
 	echo "" >> $_tf
@@ -372,7 +386,7 @@ function build_config {
 		echo "default_ca=this_ca" >> $_tf
 		echo "[ this_ca ]" >> $_tf
 	fi
-	cat $CAHOME/config/prog_$_prog >> $_tf
+	${CAT} $CAHOME/config/prog_$_prog >> $_tf
 	[ ! -z "$_dn" ] && echo "distinguished_name=req_dn" >> $_tf
 	[ ! -z "$_attrs" ] && echo "attributes=$_attrs" >> $_tf
 	[ ! -z "$_policy" ] && echo "policy=$_policy" >> $_tf
@@ -381,10 +395,10 @@ function build_config {
 	if [ ! -z "$_dn" ]; then
 		if [ -f $_dn ]; then
 			echo "[ req_dn ]" >> $_tf
-			cat $_dn >> $_tf
+			${CAT} $_dn >> $_tf
 		else
 			echo "missing DN config"
-			rm -f $_tf
+			${RM} -f $_tf
 			return 1
 		fi
 	fi
@@ -392,10 +406,10 @@ function build_config {
 	if [ ! -z $_attrs ]; then
 		if [ -f $CAHOME/config/$_attrs ]; then
 			echo "[ $_attrs ]" >> $_tf
-			cat $CAHOME/config/$_attrs >> $_tf
+			${CAT} $CAHOME/config/$_attrs >> $_tf
 		else
 			echo "missing attrs config"
-			rm -f $_tf
+			${RM} -f $_tf
 			return 1
 		fi
 	fi
@@ -403,10 +417,10 @@ function build_config {
 	if [ ! -z $_policy ]; then
 		if [ -f $CAHOME/config/$_policy ]; then
 			echo "[ $_policy ]" >> $_tf
-			cat $CAHOME/config/$_policy >> $_tf
+			${CAT} $CAHOME/config/$_policy >> $_tf
 		else
 			echo "missing policy config"
-			rm -f $_tf
+			${RM} -f $_tf
 			return 1
 		fi
 	fi
@@ -414,17 +428,17 @@ function build_config {
 	if [ ! -z $_exten ]; then
 		if [ -f $CAHOME/config/$_exten ]; then
 			echo "[ $_exten ]" >> $_tf
-			cat $CAHOME/config/$_exten >> $_tf
+			${CAT} $CAHOME/config/$_exten >> $_tf
 			# SAN MUST ALWAY BE DIRECTLY AFTER extensions
 			if [ ! -z "$_san" ]; then
 				# must always be in teh cert_ext section
 				echo "subjectAltName = @altname" >> $_tf
 				echo ""
-				cat $_san >> $_tf
+				${CAT} $_san >> $_tf
 			fi
 		else
 			echo "missing exten config"
-			rm -f $_tf
+			${RM} -f $_tf
 			return 1
 		fi
 	fi
@@ -439,7 +453,7 @@ function key_pass {
 	[ -z "$_n" ] && return 1
 	local _tf=`newtmp "key_pass: newtmp"`
 	$OS rand -hex 16 > $_tf
-	mv -f $_tf $KEYDIR/$_n.pass || return 1
+	${MV} -f $_tf $KEYDIR/$_n.pass || return 1
 	return 0
 }
 
@@ -481,8 +495,8 @@ function create_key {
 	local _tf=`newtmp "create_key: newtmp"`
 	$OS genrsa -out $_tf $_bits >/dev/null 2>&1
 	$OS rsa -aes256 -passout file:$KEYDIR/$_n.pass -in $_tf -out $KEYDIR/$_n.key >/dev/null 2>&1
-	rm -f $_tf
-	chmod 400 $KEYDIR/$_n.key
+	${RM} -f $_tf
+	${CHMOD} 400 $KEYDIR/$_n.key
 	echo $KEYDIR/$_n.key
 	return 0
 }
@@ -618,7 +632,7 @@ function create_req {
 					echo "-name must be set first"
 					return 1
 				fi 
-				if [ ! -z "$2" -a 0 -eq $(echo "$2" | grep -c -e "^-.*") ]; then
+				if [ ! -z "$2" -a 0 -eq $(echo "$2" | ${GREP} -c -e "^-.*") ]; then
 					_bits="-bits $2"
 					shift;
 				fi
@@ -705,7 +719,7 @@ function create_req {
 	[ ! -z "$_ou" ] && echo "organizationalUnitName=$_ou" >> $_tf
 	[ ! -z "$_cn" ] && echo "commonName=$_cn" >> $_tf
 	[ ! -z "$_em" ] && echo "emailAddress=$_em" >> $_tf
-	mv -f $_tf $REQDIR/$_n.dn
+	${MV} -f $_tf $REQDIR/$_n.dn
 	if [ ! -z "$_san" ]; then
 		echo "[ altname ]" > $REQDIR/$_n.san
 		for i in $_san; do
@@ -728,8 +742,8 @@ function create_req {
 		out=`$OS req -config $_tf -new -batch -key $_key -passin file:$KEYDIR/$_n.pass -out $REQDIR/$_n.req -days $_days`
 	fi
 	if [ $? -ne 0 ]; then
-		cat $_tf >&2
-		rm -f $_tf
+		${CAT} $_tf >&2
+		${RM} -f $_tf
 		echo $out
 		return 1
 	fi
@@ -738,7 +752,7 @@ function create_req {
 	else
 		echo $REQDIR/$_n.req
 	fi
-	rm -f $_tf
+	${RM} -f $_tf
 	return 0
 }
 function create_crl {
@@ -751,12 +765,12 @@ function create_crl {
 	fi
 	out=`$OS ca -config $_tf -gencrl -out $CRLDIR/$ROOTCRL -days $CRLDAYS -keyfile $KEYDIR/$SIGNKEY -passin file:$KEYDIR/${SIGNKEY%%.key}.pass 2>&1`
 	if [ $? -ne 0 ]; then
-		cat $_tf >&2
-		rm -f $_tf
+		${CAT} $_tf >&2
+		${RM} -f $_tf
 		echo $out
 		return 1
 	fi
-	rm -f $_tf
+	${RM} -f $_tf
 	echo 0
 }
 
@@ -791,11 +805,11 @@ function get_config {
 		echo "no key specified"
 		return 1
 	fi
-	_kv=`cat $CAHOME/config/$_n | grep -E -i "^$_k[[:space:]]*="`
+	_kv=`${CAT} $CAHOME/config/$_n | ${GREP} -E -i "^$_k[[:space:]]*="`
 	if [ $_v -eq 0 ]; then
 		echo $_kv
 	else
-		echo $_kv | cut -f2 -d=
+		echo $_kv | ${CUT} -f2 -d=
 	fi
 	return 0
 }
@@ -839,7 +853,7 @@ function set_config {
 		return 1
 	fi
 	# make sure we are not adding the same key
-	grep -E -c "^$_k[[:space:]]*=" $CAHOME/config/$_n >/dev/null
+	${GREP} -E -c "^$_k[[:space:]]*=" $CAHOME/config/$_n >/dev/null
 	_rc=$?
 	if [ $_adm -eq 2 -a $_rc -eq 0 ]; then
 		_adm=0
@@ -854,18 +868,18 @@ function set_config {
 	fi
 	_tf=`newtmp "set_config: newtmp"`
 	if [ $_adm -eq 0 ]; then
-		cat $CAHOME/config/$_n | sed -r "s~(^$_k[[:space:]]*=[[:space:]]*).*~\1$_v~" > $_tf
+		${CAT} $CAHOME/config/$_n | ${SED} -r "s~(^$_k[[:space:]]*=[[:space:]]*).*~\1$_v~" > $_tf
 		echo "$_k=$_v" >&2
 	else
 		if [ $_adm -eq 2 ]; then
-			cat $CAHOME/config/$_n > $_tf
+			${CAT} $CAHOME/config/$_n > $_tf
 			echo "$_k=$_v" >> $_tf
 			echo "$_k=$_v" >&2
 		else
-			cat $CAHOME/config/$_n | sed -r "/^$_k[[:space:]]*=/d" > $_tf
+			${CAT} $CAHOME/config/$_n | ${SED} -r "/^$_k[[:space:]]*=/d" > $_tf
 		fi
 	fi
-	mv -f $_tf $CAHOME/config/$_n
+	${MV} -f $_tf $CAHOME/config/$_n
 	return 0
 }
 
@@ -929,17 +943,17 @@ function sign_req {
 	out=`$OS ca -batch -config $_tf -out $CERTDIR/$_n.crt -in $_file -keyfile $KEYDIR/$SIGNKEY -passin file:$KEYDIR/${SIGNKEY%%.key}.pass -cert $CERTDIR/$SIGNCERT -days $_days`
 #	out=`$OS ca -verbose -batch -config $_tf -out $CERTDIR/$_n.crt -in $_file -keyfile $KEYDIR/$SIGNKEY -cert $CERTDIR/$SIGNCERT -in $REQDIR/$_n.req -days $_days`
 	if [ $? -ne 0 ]; then
-		cat $_tf >&2
-		rm -f $_tf
+		${CAT} $_tf >&2
+		${RM} -f $_tf
 		echo $out
 		return 1
 	fi
 	# rename req if it is in our reqdir
 	out=${_file##*.}
 	if [ ! -z "$_n" -a "$out" == "req" ]; then
-		mv -f $REQDIR/$_n.req $REQDIR/$_n.signed
+		${MV} -f $REQDIR/$_n.req $REQDIR/$_n.signed
 	fi
-	rm -f $_tf
+	${RM} -f $_tf
 	return 0
 }
 
@@ -952,7 +966,7 @@ function list_certs {
 	local _list
 	set -o noglob
 	for i in `find $CERTDIR/ -name $_n.crt -print`; do
-		_n=`$OS x509 -in $i -noout -text | egrep "CA:TRUE" | tr -d " "`
+		_n=`$OS x509 -in $i -noout -text | ${EGREP} "CA:TRUE" | ${TR} -d " "`
 		case $_signing in
 			0) _list="${_list} $i" ;;
 			1) [[ ! -z "$_n" ]] && _list="${_list} $i" ;;
@@ -1085,10 +1099,10 @@ function revoke_cert {
 			echo "cannot find cert with by name $_n"
 			return 1
 		fi
-		_s=`echo $out | sed 's/.*=//'`
+		_s=`echo $out | ${SED} 's/.*=//'`
 	fi
 	# cleanup non-hex char
-	_s=`echo $_s | tr -c -d "[:xdigit:]" | tr "[:lower:]" "[:upper:]"`
+	_s=`echo $_s | ${TR} -c -d "[:xdigit:]" | ${TR} "[:lower:]" "[:upper:]"`
 	_tf=`build_config "$_ca" "ca"`
 	if [ $? -ne 0 ]; then
 		echo $_tf
@@ -1096,12 +1110,12 @@ function revoke_cert {
 	fi
 	out=`$OS ca -config $_tf -keyfile $KEYDIR/$SIGNKEY -passin file:$KEYDIR/${SIGNKEY%%.key}.pass -revoke $LIBDIR/$_s.pem`
 	if [ $? -ne 0 ]; then
-		cat $_tf
-		rm -f $tf
+		${CAT} $_tf
+		${RM} -f $tf
 		echo $out
 		return 1
 	fi
-	rm -f $_tf
+	${RM} -f $_tf
 	if [ $_crl -eq 1 ]; then
 		out=`create_crl $_ca`
 		if [ $? -ne 0 ]; then
@@ -1204,7 +1218,7 @@ function import_config {
 		echo "must specify file"
 		return 1
 	fi
-	cp -f $_f $CAHOME/config/$_n
+	${CP} -f $_f $CAHOME/config/$_n
 	return 0
 }
 
@@ -1252,7 +1266,7 @@ function delete_file {
 	_fe=`eval echo $_fe`
 	for i in `find $_d \( $_fe \)  -print`; do
 		echo "Removing ${i##*/}" >&2
-		rm -f $i
+		${RM} -f $i
 	done
 	return 0
 }
@@ -1268,22 +1282,22 @@ function get_pass_from_input {
 	case "$_p" in
 		-) # read from stdin
 			_p=`read_from_stdin "Enter Password:" -noecho`
-			cat <<EOF>$_pf
+			${CAT} <<EOF>$_pf
 $_p
 EOF
 			;;
 		file:*) # read from file
 			if [ -f ${_p##file:} ]; then
 				_p=${_p##file:}
-				cat $_p >$_pf
+				${CAT} $_p >$_pf
 			else
 				echo "cannot find password file"
-				rm -f $_pf
+				${RM} -f $_pf
 				return 1
 			fi
 			;;
 		*)	# password specified
-			cat <<EOF>$_pf
+			${CAT} <<EOF>$_pf
 $_p
 EOF
 			;;
@@ -1334,10 +1348,10 @@ function export_pkcs12 {
 	if [ -f $_f ]; then 
 		if [ $_ow -ne 1 ]; then
 			echo "file already exists.  use -overwrite to overwrite"
-			rm -f $_pf
+			${RM} -f $_pf
 			return 1
 		else
-			rm -f $_f
+			${RM} -f $_f
 		fi
 	fi
 	_pf=`get_pass_from_input "$_p"`
@@ -1347,17 +1361,17 @@ function export_pkcs12 {
 	fi
 	if [ ! -s "$_pf" ]; then
 		echo "no password specified"
-		rm -f $_pf
+		${RM} -f $_pf
 		return 1
 	fi
 	if [ ! -f $CERTDIR/$_n.crt ]; then
 		echo "cannot find cert"
-		rm -f $_pf
+		${RM} -f $_pf
 		return 1
 	fi
 	if [ ! -f $KEYDIR/$_n.key ]; then
 		echo "cannot find key"
-		rm -f $_pf
+		${RM} -f $_pf
 		return 1
 	fi
 	if [ $_ch -eq 1 ]; then
@@ -1365,12 +1379,12 @@ function export_pkcs12 {
 	fi
 	out=`$OS pkcs12 -aes256 -export -in $CERTDIR/$_n.crt -inkey $KEYDIR/$_n.key -passin file:$KEYDIR/$_n.pass -out $_f -passout file:$_pf $_chain`
 	if [ $? -ne 0 ]; then
-		rm -f $_pf
+		${RM} -f $_pf
 		echo "error extracting cert"
 		echo $out
 		return 1
 	fi
-	rm -f $_pf
+	${RM} -f $_pf
 	return 0
 }
 
@@ -1416,33 +1430,33 @@ function import_pkcs12 {
 	fi
 	if [ ! -s "$_pf" ]; then
 		echo "no password specified"
-		rm -f $_pf
+		${RM} -f $_pf
 		return 1
 	fi
 	if [ -f $CERTDIR/$_n.crt ]; then
 		if [ $_ow -eq 1 ]; then
-			rm -f $CERTDIR/$_n.crt
+			${RM} -f $CERTDIR/$_n.crt
 		else
 			echo "cert already exists.  use -overwrite to overwrite"
-			rm -f $_pf
+			${RM} -f $_pf
 			return 1
 		fi
 	fi
 	if [ -f $KEYDIR/$_n.key ]; then
 		if [ $_ow -eq 1 ]; then
-			rm -f $KEYDIR/$_n.key
-			rm -f $KEYDIR/$_n.pass
+			${RM} -f $KEYDIR/$_n.key
+			${RM} -f $KEYDIR/$_n.pass
 		else
 			echo "key already exists.  use -overwrite to overwrite"
-			rm -f $_pf
+			${RM} -f $_pf
 			return 1
 		fi
 	fi
 	# extract certificate
 	out=`$OS pkcs12 -in $_f -nokeys -clcerts -out $CERTDIR/$_n.crt -passin file:$_pf`
 	if [ $? -ne 0 ]; then
-		rm -f $CERTDIR/$_n.crt
-		rm -f $_pf
+		${RM} -f $CERTDIR/$_n.crt
+		${RM} -f $_pf
 		echo "error extracting cert"
 		echo $out
 		return 1
@@ -1451,21 +1465,21 @@ function import_pkcs12 {
 	key_pass $_ca $_n
 	if [ $? -ne 0 ]; then
 		echo "error generating key pass"
-		rm -f $_pf
+		${RM} -f $_pf
 		return 1
 	fi
 	# extract key
 	out=`$OS pkcs12 -in $_f -nocerts -passout file:$KEYDIR/$_n.pass -out $KEYDIR/$_n.key -passin file:$_pf`
 	if [ $? -ne 0 ]; then
-		rm -f $KEYDIR/$_n.pass
-		rm -f $KEYDIR/$_n.key
-		rm -f $_pf
+		${RM} -f $KEYDIR/$_n.pass
+		${RM} -f $KEYDIR/$_n.key
+		${RM} -f $_pf
 		echo "error extracting key"
 		echo $out
 		return 1
 	fi
 	# DO NOT import the chain
-	rm -f $_pf
+	${RM} -f $_pf
 	return 0
 }
 
@@ -1493,20 +1507,20 @@ function export_html {
 		die 1 "no output file"
 	fi
 	_td=`newtmpd "export_html: newtmpd"`
-	mkdir $_td/ca || die 1 "export_html: failed to make directory"
+	${MKDIR} $_td/ca || die 1 "export_html: failed to make directory"
 	set -o noglob
 	_cert_list=`list_certs "*" 1`
 	set +o noglob
 	for _tf in $_cert_list; do
-		cp $_tf $_td/ca
+		${CP} $_tf $_td/ca
 	done
-	cp $CRLDIR/$ROOTCRL $_td/ca
+	${CP} $CRLDIR/$ROOTCRL $_td/ca
 	_tf=`newtmp "export_html: newtmp"`
-	tar -zcf $_tf -C $_td .
+	${TAR} -zcf $_tf -C $_td .
 	if [ -f $_f -a $_ow -eq 0 ]; then
 		die 1 "cannot create export. File already exists"
 	fi
-	mv -f $_tf $_f
+	${MV} -f $_tf $_f
 	return 0
 }
 
@@ -1524,8 +1538,8 @@ function export_html {
 #		echo $out
 #		return 2
 #	fi
-#	_sub=`echo $_sub | cut -f2- -d=`
-#	_iss=`echo $_iss | cut -f2- -d=`
+#	_sub=`echo $_sub | ${CUT} -f2- -d=`
+#	_iss=`echo $_iss | ${CUT} -f2- -d=`
 #	if [ "$_sub" = "$_iss" ]; then
 #		# we have root
 #		return 0
@@ -1541,7 +1555,7 @@ function generate_chain {
 	if [ -z "$_calist" ]; then
 		die 1 "could not find any CA certs"
 	fi
-	cat $_calist > $CERTDIR/$ROOTCHAIN
+	${CAT} $_calist > $CERTDIR/$ROOTCHAIN
 	return 0
 }
 
@@ -1615,24 +1629,24 @@ while [ $# -ne 0 ]; do
 					[ -z "$2" ] && die 1 "nothing to do"
 					case "$2" in
 						mac*)
-							cat $CAHOME/config/macros
+							${CAT} $CAHOME/config/macros
 							;;
 						pol*)
 							for i in `ls $CAHOME/config/policy_*`; do
 								echo "___ ${i##*/} ___"
-								cat $i
+								${CAT} $i
 							done
 							;;
 						ext*)
 							for i in `ls $CAHOME/config/extension_*`; do
 								echo "___ ${i##*/} ___"
-								cat $i
+								${CAT} $i
 							done
 							;;
 						prog*)
 							for i in `ls $CAHOME/config/prog_*`; do
 								echo "___ ${i##*/} ___"
-								cat $i
+								${CAT} $i
 							done
 							;;
 						*)
